SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL';

DROP DATABASE IF EXISTS todomvc;
CREATE DATABASE todomvc
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_unicode_ci;

USE todomvc;

CREATE TABLE IF NOT EXISTS `todos` (
  `id`     BIGINT UNSIGNED NOT NULL,
  `name`   VARCHAR(255)    NOT NULL,
  `status` VARCHAR(255)    NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;